# pebblecoind which starts from pre-made blockchain

FROM pebblecoind_base

ADD ./blockchain.bin                   /daemon/data/blockchain.bin
ADD ./blockchaindb_alt_entries.bin     /daemon/data/blockchaindb_alt_entries.bin
ADD ./blockchaindb_blocks.bin          /daemon/data/blockchaindb_blocks.bin
ADD ./blockchaindb_entries.bin         /daemon/data/blockchaindb_entries.bin
ADD ./blockchaindb_index.bin           /daemon/data/blockchaindb_index.bin
ADD ./blockchaindb_invalid_entries.bin /daemon/data/blockchaindb_invalid_entries.bin
ADD ./blockchaindb_txs.bin             /daemon/data/blockchaindb_txs.bin
ADD ./hashcache.bin                    /daemon/data/hashcache.bin
